server:
  port: 8081
  servlet:
    context-path: /market


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;
    username: geek
    password: geek
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    encoding: UTF-8
